package cmdb

import (
	"errors"
	"fmt"
	"strings"
)

var ErrInvalid = errors.New("invalid input")

type NodeKind string

const (
	Identity    NodeKind = "identity"
	JobCode     NodeKind = "job-code"
	Birthright  NodeKind = "birthright"
	Role        NodeKind = "role"
	Entitlement NodeKind = "entitlement"
	CI          NodeKind = "ci"
	Incident    NodeKind = "incident"
	Change      NodeKind = "change"
	Event       NodeKind = "event"
)

type CIType string

const (
	Server        CIType = "server"
	Printer       CIType = "printer"
	DataConnector CIType = "data-connector"
	Application   CIType = "application"
)

type nodeSpec struct {
	label string
	key   string
}

var nodeSpecs = map[NodeKind]nodeSpec{
	Identity:    {label: "Identity", key: "id"},
	JobCode:     {label: "JobCode", key: "code"},
	Birthright:  {label: "Birthright", key: "id"},
	Role:        {label: "Role", key: "id"},
	Entitlement: {label: "Entitlement", key: "id"},
	CI:          {label: "CI", key: "id"},
	Incident:    {label: "Incident", key: "id"},
	Change:      {label: "Change", key: "id"},
	Event:       {label: "Event", key: "id"},
}

type RelationshipKind string

const (
	HasJobCode   RelationshipKind = "has-job-code"
	QualifiesFor RelationshipKind = "qualifies-for"
	Grants       RelationshipKind = "grants"
	Includes     RelationshipKind = "includes"
	Affects      RelationshipKind = "affects"
	Changes      RelationshipKind = "changes"
	ObservedOn   RelationshipKind = "observed-on"
	DependsOn    RelationshipKind = "depends-on"
	HostedOn     RelationshipKind = "hosted-on"
	Uses         RelationshipKind = "uses"
	UsedBy       RelationshipKind = "used-by"
)

type relationshipSpec struct {
	typeName string
	from     NodeKind
	to       NodeKind
}

type RelationshipDefinition struct {
	TypeName string
	From     NodeKind
	To       NodeKind
}

var relationshipSpecs = map[RelationshipKind]relationshipSpec{
	HasJobCode:   {typeName: "HAS_JOB_CODE", from: Identity, to: JobCode},
	QualifiesFor: {typeName: "QUALIFIES_FOR", from: JobCode, to: Birthright},
	Grants:       {typeName: "GRANTS", from: Birthright, to: Role},
	Includes:     {typeName: "INCLUDES", from: Role, to: Entitlement},
	Affects:      {typeName: "AFFECTS", from: Incident, to: CI},
	Changes:      {typeName: "CHANGES", from: Change, to: CI},
	ObservedOn:   {typeName: "OBSERVED_ON", from: Event, to: CI},
	DependsOn:    {typeName: "DEPENDS_ON", from: CI, to: CI},
	HostedOn:     {typeName: "HOSTED_ON", from: CI, to: CI},
	Uses:         {typeName: "USES", from: CI, to: CI},
	UsedBy:       {typeName: "USED_BY", from: CI, to: CI},
}

type Node struct {
	Kind          NodeKind       `json:"kind"`
	ID            string         `json:"id"`
	Properties    map[string]any `json:"properties,omitempty"`
	Status        string         `json:"status"`
	RetiredAt     string         `json:"retiredAt,omitempty"`
	Relationships []Relationship `json:"relationships,omitempty"`
}

type Relationship struct {
	Kind       RelationshipKind `json:"kind"`
	FromID     string           `json:"fromId"`
	ToID       string           `json:"toId"`
	Properties map[string]any   `json:"properties,omitempty"`
	Status     string           `json:"status"`
	RetiredAt  string           `json:"retiredAt,omitempty"`
}

func ParseNodeKind(value string) (NodeKind, error) {
	kind := NodeKind(strings.ToLower(strings.TrimSpace(value)))
	if _, ok := nodeSpecs[kind]; !ok {
		return "", fmt.Errorf("%w: unsupported node kind %q", ErrInvalid, value)
	}
	return kind, nil
}

func ParseRelationshipKind(value string) (RelationshipKind, error) {
	kind := RelationshipKind(strings.ToLower(strings.TrimSpace(value)))
	if _, ok := relationshipSpecs[kind]; !ok {
		kind = RelationshipKind(strings.ToLower(strings.ReplaceAll(strings.TrimSpace(value), "_", "-")))
	}
	if _, ok := relationshipSpecs[kind]; !ok {
		return "", fmt.Errorf("%w: unsupported relationship kind %q", ErrInvalid, value)
	}
	return kind, nil
}

func ParseCIType(value string) (CIType, error) {
	kind := CIType(strings.ToLower(strings.ReplaceAll(strings.TrimSpace(value), " ", "-")))
	switch kind {
	case Server, Printer, DataConnector, Application:
		return kind, nil
	default:
		return "", fmt.Errorf("%w: unsupported CI type %q; allowed types are %s", ErrInvalid, value, strings.Join(CITypeNames(), ", "))
	}
}

func RequiresGeneratedID(kind NodeKind) bool {
	_, supported := nodeSpecs[kind]
	return supported
}

func GeneratedIDPrefix(kind NodeKind) (string, error) {
	switch kind {
	case Identity:
		return "IDN", nil
	case JobCode:
		return "JOB", nil
	case Birthright:
		return "BIR", nil
	case Role:
		return "ROLE", nil
	case Entitlement:
		return "ENT", nil
	case CI:
		return "CI", nil
	case Incident:
		return "INC", nil
	case Change:
		return "CHG", nil
	case Event:
		return "EVT", nil
	default:
		return "", fmt.Errorf("%w: %s IDs are not generated by the application", ErrInvalid, kind)
	}
}

func CITypeNames() []string {
	return []string{string(Server), string(Printer), string(DataConnector), string(Application)}
}

func NodeKinds() []NodeKind {
	return []NodeKind{Identity, JobCode, Birthright, Role, Entitlement, CI, Incident, Change, Event}
}

func RelationshipKinds() []RelationshipKind {
	return []RelationshipKind{HasJobCode, QualifiesFor, Grants, Includes, Affects, Changes, ObservedOn, DependsOn, HostedOn, Uses, UsedBy}
}

func NodeDefinition(kind NodeKind) (label, key string, err error) {
	spec, ok := nodeSpecs[kind]
	if !ok {
		return "", "", fmt.Errorf("unsupported node kind %q", kind)
	}
	return spec.label, spec.key, nil
}

func RelationshipDefinitionFor(kind RelationshipKind) (RelationshipDefinition, error) {
	spec, ok := relationshipSpecs[kind]
	if !ok {
		return RelationshipDefinition{}, fmt.Errorf("unsupported relationship kind %q", kind)
	}
	return RelationshipDefinition{TypeName: spec.typeName, From: spec.from, To: spec.to}, nil
}
